@startuml

participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber

クライアントA -> サーバー:退室
クライアントB <- サーバー:クライアントAが退室しました
クライアントC <- サーバー:クライアントAが退室しました
クライアントB -> サーバー:退室
クライアントA <- サーバー:クライアントBが退室しました
クライアントC <- サーバー:クライアントBが退室しました
クライアントC -> サーバー:退室
クライアントA <- サーバー: クライアントCが退室しました
クライアントB <- サーバー: クライアントCが退室しました

@enduml