@startuml
'botシーケンス図


participant クライアントA
participant クライアントB
participant クライアントC
participant サーバー

autonumber

クライアントA -> サーバー:入室
クライアントA <- サーバー:クライアントAが入室しました
クライアントB -> サーバー:入室
クライアントA <- サーバー:クライアントBが入室しました
クライアントB <- サーバー:クライアントBが入室しました
クライアントC -> サーバー:入室
クライアントA <- サーバー: クライアントCが入室しました
クライアントB <- サーバー: クライアントCが入室しました
クライアントC <- サーバー: クライアントCが入室しました
@enduml '図の終了